language: java
install: true

jdk: oraclejdk11

addons:
  sonarcloud:
    organization: "proftaak-semester3"
    token:
      secure: 99a4086659ca818cc92e38308551bb10737d36f8 # encrypted value of your token

script:
  #- ./gradlew build --scan -s
  - ./gradlew clean test
  - ./gradlew clean check sonarqube build
  #- ./gradlew sonarqube
